import type { NipuxSummary } from "./types";

export const mockSummary: NipuxSummary = {
  product: "Nipux",
  system: {
    hostname: "local-workstation",
    platform: "Darwin",
    release: "24.x",
    arch: "arm64",
    chip_name: "Apple M3",
    apple_silicon: true,
    cpu_model: "Apple M3",
    cpu_cores_logical: 8,
    cpu_cores_physical: 8,
    ram_gb: 16,
    disk_free_gb: 114.2,
    disk_total_gb: 512,
    gpus: [
      {
        id: "apple-unified-gpu",
        vendor: "Apple",
        name: "Apple M3",
        vram_gb: 12,
        memory_bandwidth_gbps: 100,
        driver: "Metal 4",
        power_limit_watts: null,
        memory_kind: "unified",
        shared_memory_gb: 16,
      },
    ],
  },
  hermes: {
    installed: false,
    version: null,
    binary: null,
    managed_home: "~/.local/share/nipux/hermes-home",
    managed_profile: "~/.local/share/nipux/hermes-home/profiles/nipux",
    strategy: "Subprocess boundary with Nipux-owned profile paths and config.",
    environment: {
      HERMES_HOME: "~/.local/share/nipux/hermes-home",
      HERMES_PROFILE: "nipux",
      NIPUX_MANAGED: "1",
      NIPUX_MODEL_ENDPOINT: "http://127.0.0.1:8000/v1",
    },
  },
  runtime: {
    id: "mlx",
    label: "MLX",
    reason: "Apple Silicon detected. Prefer MLX for unified-memory local inference.",
  },
  recommendation: {
    supported: true,
    selected_model_id: "carnice-9b-mlx-4bit",
    effective_vram_gb: 12,
    estimated_tokens_per_second: 29.4,
    estimated_cost_per_million_tokens_usd: 0.08,
    reason: "Selected Carnice 9B 4-bit for 12 GB usable unified memory.",
    platform_track: "mlx",
    selected: {
      id: "carnice-9b-mlx-4bit",
      family: "Carnice",
      size: "9B",
      quantization: "4-bit",
      runtime: "mlx",
      artifact_kind: "mlx",
      min_vram_gb: 12,
      target_vram_gb: 8.5,
      target_ram_gb: 16,
      repo: "https://huggingface.co/kai-os/Carnice-9b-MLX",
      filename: "mlx-4bit",
      notes: "Apple Silicon path via MLX. Repo assumed to exist for planning.",
    },
  },
  install_plan: {
    estimated_disk_needed_gb: 11.5,
    requires_confirmation: true,
    warnings: [
      "Hermes Agent is not installed yet and will need to be bootstrapped.",
    ],
    steps: [
      "Wait for the user to confirm the plan inside the Nipux onboarding flow.",
      "Create a Nipux-managed Hermes home and profile directory.",
      "Install or validate the MLX runtime.",
      "Download the recommended Carnice build.",
      "Generate a Nipux-owned Hermes config that targets the local model endpoint.",
      "Expose the Nipux UI on the local network and keep Hermes behind the daemon boundary.",
    ],
  },
  model_catalog: [
    {
      id: "carnice-9b-mlx-4bit",
      family: "Carnice",
      size: "9B",
      quantization: "4-bit",
      runtime: "mlx",
      artifact_kind: "mlx",
      min_vram_gb: 12,
      target_vram_gb: 8.5,
      target_ram_gb: 16,
      repo: "https://huggingface.co/kai-os/Carnice-9b-MLX",
      filename: "mlx-4bit",
      notes: "Apple Silicon path via MLX. Repo assumed to exist for planning.",
    },
    {
      id: "carnice-9b-mlx-8bit",
      family: "Carnice",
      size: "9B",
      quantization: "8-bit",
      runtime: "mlx",
      artifact_kind: "mlx",
      min_vram_gb: 24,
      target_vram_gb: 14,
      target_ram_gb: 24,
      repo: "https://huggingface.co/kai-os/Carnice-9b-MLX",
      filename: "mlx-8bit",
      notes: "Higher-quality Apple Silicon path via MLX.",
    },
  ],
  runtime_catalog: [
    {
      id: "vllm",
      label: "vLLM",
      best_for: "NVIDIA or high-end ROCm hosts with enough VRAM for sustained serving.",
      install_size_gb: 7.5,
      network_exposed: true,
      supports_apple: false,
    },
    {
      id: "llama.cpp",
      label: "llama.cpp",
      best_for: "Broadest compatibility, GGUF quantization ladder, and smaller machines.",
      install_size_gb: 2.5,
      network_exposed: true,
      supports_apple: true,
    },
    {
      id: "mlx",
      label: "MLX",
      best_for: "Apple Silicon hosts running unified-memory local inference with mlx-lm.",
      install_size_gb: 3,
      network_exposed: true,
      supports_apple: true,
    },
  ],
};
