import type { HermesSettingsSummary, NipuxSummary } from "./types";

export const mockSummary: NipuxSummary = {
  product: "Nipux",
  system: {
    hostname: "nipux-local",
    platform: "Darwin",
    release: "25.3.0",
    arch: "arm64",
    chip_name: "Apple M3",
    apple_silicon: true,
    cpu_model: "Apple M3",
    cpu_cores_logical: 8,
    cpu_cores_physical: 8,
    ram_gb: 16,
    disk_free_gb: 114.2,
    disk_total_gb: 512,
    gpus: [
      {
        id: "apple-unified-gpu",
        vendor: "Apple",
        name: "Apple M3",
        vram_gb: 12,
        memory_bandwidth_gbps: 100,
        driver: "Metal 4",
        memory_kind: "unified",
        shared_memory_gb: 16,
      },
    ],
  },
  telemetry: {
    cpu_percent: 12.4,
    ram_used_gb: 4.2,
    ram_total_gb: 16,
    node_count: 4,
    active_nodes: 2,
    active_sessions: 1,
    total_sessions: 28,
    total_tokens: 412384,
    total_throughput_tps: 38.4,
  },
  hermes: {
    installed: true,
    configured: true,
    version: "Hermes Agent v1.0.0",
    binary: "/opt/hermes/bin/hermes",
    home: "/Users/kaistephens/.hermes",
    config_path: "/Users/kaistephens/.hermes/config.yaml",
    env_path: "/Users/kaistephens/.hermes/.env",
    state_db_path: "/Users/kaistephens/.hermes/state.db",
    logs_path: "/Users/kaistephens/.hermes/logs/errors.log",
    gateway_running: false,
    install_command:
      "curl -fsSL https://raw.githubusercontent.com/NousResearch/hermes-agent/main/scripts/install.sh | bash",
  },
  settings: {
    installed: true,
    configured: true,
    binary: "/opt/hermes/bin/hermes",
    home: "/Users/kaistephens/.hermes",
    config_path: "/Users/kaistephens/.hermes/config.yaml",
    env_path: "/Users/kaistephens/.hermes/.env",
    model: "kai-os/Carnice-9b-GGUF",
    toolsets: ["browser", "terminal", "file", "clarify"],
    max_turns: 80,
    terminal_backend: "local",
    terminal_cwd: ".",
    compression_enabled: true,
    compression_threshold: 0.9,
    display_personality: "nipux",
    openai_base_url: "http://127.0.0.1:8014/v1",
    openrouter_api_key_set: false,
    openrouter_api_key_hint: "",
    openai_api_key_set: true,
    openai_api_key_hint: "sk-o•••••••1a2b",
  },
  runtime_state: {
    status: "running",
    model_loaded: true,
    active_model_id: "kai-os/Carnice-9b-GGUF",
    recommended_model_id: "kai-os/Carnice-9b-GGUF",
    endpoint: "http://127.0.0.1:8014/v1",
    started_at: 1776041800,
  },
  nodes: [
    {
      id: "browser",
      identifier: "NODE_01",
      label: "Browser agent",
      status: "active",
      mode: "Isolated session",
      model: "kai-os/Carnice-9b-GGUF",
      latency_ms: 142.0,
      tokens_per_sec: 24.8,
      total_tokens: 182400,
      uptime_seconds: 1180,
      description: "Web search, browsing, and extraction in an isolated agent session.",
      trend: [18, 32, 46, 34],
    },
    {
      id: "code",
      identifier: "NODE_02",
      label: "Code agent",
      status: "idle",
      mode: "Isolated session",
      model: "kai-os/Carnice-9b-GGUF",
      latency_ms: 0,
      tokens_per_sec: 0,
      total_tokens: 42100,
      uptime_seconds: 0,
      description: "Repository work, patching, and file-heavy tasks through Hermes.",
      trend: [10, 12, 14, 11],
    },
    {
      id: "terminal",
      identifier: "NODE_03",
      label: "Terminal agent",
      status: "active",
      mode: "Isolated session",
      model: "kai-os/Carnice-9b-GGUF",
      latency_ms: 208.0,
      tokens_per_sec: 13.6,
      total_tokens: 91720,
      uptime_seconds: 804,
      description: "Command execution and environment bring-up with approvals.",
      trend: [28, 24, 30, 26],
    },
    {
      id: "orchestrator",
      identifier: "NODE_04",
      label: "Orchestrator",
      status: "idle",
      mode: "Supervisor session",
      model: "kai-os/Carnice-9b-GGUF",
      latency_ms: 0,
      tokens_per_sec: 0,
      total_tokens: 0,
      uptime_seconds: 0,
      description: "A top-level agent that can route work across the other surfaces.",
      trend: [8, 8, 8, 8],
    },
  ],
  log_lines: [
    "[14:02:11.23] SYS_INIT: Booting agentic subroutine primary...",
    "[14:02:12.01] INF: Establishing Hermes profile handshake... SUCCESS",
    "[14:02:13.12] INF: Loading cognitive weights... [1.4GB]",
    "[14:02:15.55] EVENT: Interaction detected at NODE_01",
    "[14:02:16.12] PROC: Sampling latent space [K=40, P=0.95]",
    "[14:02:17.33] ACT: Executing local browser query via Hermes tools",
    "[14:02:18.01] INF: Response synthesis initiated...",
    "[14:03:01.05] SYS: Heartbeat stable. Temp: 42C.",
  ],
  usage_summary: {
    prompt_tokens: 308122,
    completion_tokens: 104262,
    total_tokens: 412384,
    requests: 28,
    tool_calls: 91,
    api_equivalent_cost_usd: 0.031,
    savings_vs_api_usd: 0.031,
  },
  api_reference: {
    provider: "OpenRouter",
    model_id: "qwen/qwen3.5-9b",
    label: "Qwen: Qwen3.5-9B",
    prompt_per_million_usd: 0.05,
    completion_per_million_usd: 0.15,
    blended_per_million_usd: 0.2,
    context_length: 256000,
    source_url: "https://openrouter.ai/qwen/qwen3.5-9b",
    checked_at: 1776038400,
  },
  agents: [],
};

export const mockSettings: HermesSettingsSummary = mockSummary.settings;
