from __future__ import annotations

MODEL_CATALOG = [
    {
        "id": "carnice-9b-mlx-4bit",
        "family": "Carnice",
        "size": "9B",
        "quantization": "4-bit",
        "runtime": "mlx",
        "artifact_kind": "mlx",
        "min_vram_gb": 12.0,
        "target_vram_gb": 8.5,
        "target_ram_gb": 16.0,
        "repo": "https://huggingface.co/kai-os/Carnice-9b-MLX",
        "filename": "mlx-4bit",
        "notes": "Apple Silicon path via MLX. Repo assumed to exist for planning.",
    },
    {
        "id": "carnice-9b-mlx-8bit",
        "family": "Carnice",
        "size": "9B",
        "quantization": "8-bit",
        "runtime": "mlx",
        "artifact_kind": "mlx",
        "min_vram_gb": 24.0,
        "target_vram_gb": 14.0,
        "target_ram_gb": 24.0,
        "repo": "https://huggingface.co/kai-os/Carnice-9b-MLX",
        "filename": "mlx-8bit",
        "notes": "Higher-quality Apple Silicon path via MLX.",
    },
    {
        "id": "carnice-27b-mlx-4bit",
        "family": "Carnice",
        "size": "27B",
        "quantization": "4-bit",
        "runtime": "mlx",
        "artifact_kind": "mlx",
        "min_vram_gb": 32.0,
        "target_vram_gb": 23.0,
        "target_ram_gb": 36.0,
        "repo": "https://huggingface.co/kai-os/Carnice-27b-MLX",
        "filename": "mlx-4bit",
        "notes": "Apple Silicon 27B path. Repo assumed to exist for planning.",
    },
    {
        "id": "carnice-27b-mlx-8bit",
        "family": "Carnice",
        "size": "27B",
        "quantization": "8-bit",
        "runtime": "mlx",
        "artifact_kind": "mlx",
        "min_vram_gb": 64.0,
        "target_vram_gb": 44.0,
        "target_ram_gb": 64.0,
        "repo": "https://huggingface.co/kai-os/Carnice-27b-MLX",
        "filename": "mlx-8bit",
        "notes": "Top-end unified-memory Apple Silicon path.",
    },
    {
        "id": "carnice-9b-q4km",
        "family": "Carnice",
        "size": "9B",
        "quantization": "Q4_K_M",
        "runtime": "llama.cpp",
        "artifact_kind": "gguf",
        "min_vram_gb": 8.0,
        "target_vram_gb": 5.6,
        "target_ram_gb": 8.0,
        "repo": "https://huggingface.co/kai-os/Carnice-9b-GGUF",
        "filename": "Carnice-9b-Q4_K_M.gguf",
        "notes": "Compatibility-first local profile.",
    },
    {
        "id": "carnice-9b-q6",
        "family": "Carnice",
        "size": "9B",
        "quantization": "Q6_K",
        "runtime": "llama.cpp",
        "artifact_kind": "gguf",
        "min_vram_gb": 12.0,
        "target_vram_gb": 7.4,
        "target_ram_gb": 10.0,
        "repo": "https://huggingface.co/kai-os/Carnice-9b-GGUF",
        "filename": "Carnice-9b-Q6_K.gguf",
        "notes": "Balanced 9B profile for mid-tier GPUs.",
    },
    {
        "id": "carnice-9b-q8",
        "family": "Carnice",
        "size": "9B",
        "quantization": "Q8_0",
        "runtime": "llama.cpp",
        "artifact_kind": "gguf",
        "min_vram_gb": 16.0,
        "target_vram_gb": 9.8,
        "target_ram_gb": 12.0,
        "repo": "https://huggingface.co/kai-os/Carnice-9b-GGUF",
        "filename": "Carnice-9b-Q8_0.gguf",
        "notes": "Highest-quality 9B local path.",
    },
    {
        "id": "carnice-27b-q4km",
        "family": "Carnice",
        "size": "27B",
        "quantization": "Q4_K_M",
        "runtime": "llama.cpp",
        "artifact_kind": "gguf",
        "min_vram_gb": 24.0,
        "target_vram_gb": 16.8,
        "target_ram_gb": 24.0,
        "repo": "https://huggingface.co/kai-os/Carnice-27b-GGUF",
        "filename": "Carnice-27b-Q4_K_M.gguf",
        "notes": "27B entry point. Repo assumed to exist for planning.",
    },
    {
        "id": "carnice-27b-q6",
        "family": "Carnice",
        "size": "27B",
        "quantization": "Q6_K",
        "runtime": "llama.cpp",
        "artifact_kind": "gguf",
        "min_vram_gb": 28.0,
        "target_vram_gb": 22.9,
        "target_ram_gb": 30.0,
        "repo": "https://huggingface.co/kai-os/Carnice-27b-GGUF",
        "filename": "Carnice-27b-Q6_K.gguf",
        "notes": "High-fidelity 27B profile for strong local boxes.",
    },
    {
        "id": "carnice-27b-q8",
        "family": "Carnice",
        "size": "27B",
        "quantization": "Q8_0",
        "runtime": "llama.cpp",
        "artifact_kind": "gguf",
        "min_vram_gb": 32.0,
        "target_vram_gb": 29.6,
        "target_ram_gb": 36.0,
        "repo": "https://huggingface.co/kai-os/Carnice-27b-GGUF",
        "filename": "Carnice-27b-Q8_0.gguf",
        "notes": "Top-end local 27B quality. Repo assumed to exist for planning.",
    },
]

RUNTIME_PROFILES = [
    {
        "id": "vllm",
        "label": "vLLM",
        "best_for": "NVIDIA or high-end ROCm hosts with enough VRAM for sustained serving.",
        "install_size_gb": 7.5,
        "network_exposed": True,
        "supports_apple": False,
    },
    {
        "id": "llama.cpp",
        "label": "llama.cpp",
        "best_for": "Broadest compatibility, GGUF quantization ladder, and smaller machines.",
        "install_size_gb": 2.5,
        "network_exposed": True,
        "supports_apple": True,
    },
    {
        "id": "mlx",
        "label": "MLX",
        "best_for": "Apple Silicon hosts running unified-memory local inference with mlx-lm.",
        "install_size_gb": 3.0,
        "network_exposed": True,
        "supports_apple": True,
    },
]
